export const runtimeScripts = [
  "app.js",
  "boot.js",
  "core/app-map-controller.js",
  "core/app-setup.js",
  "core/camera.js",
  "core/camera-gestures.js",
  "core/copy.js",
  "core/debug.js",
  "core/dom-ids.js",
  "core/dom.js",
  "core/frame-loop.js",
  "core/game-controller.js",
  "core/goal-controller.js",
  "core/game-lifecycle.js",
  "core/game-loop.js",
  "core/geometry.js",
  "core/game-config.js",
  "core/haptics.js",
  "core/intro-sequence.js",
  "core/intro-timers.js",
  "core/map-bounds.js",
  "core/map-config.js",
  "core/map-elements.js",
  "core/map-obstacles.js",
  "core/map-progression.js",
  "core/map-reachability.js",
  "core/map-runtime.js",
  "core/map-state.js",
  "core/map-validation-messages.js",
  "core/map-validation.js",
  "core/map-variants.js",
  "core/map.js",
  "core/physics-collisions.js",
  "core/physics.js",
  "core/procedural-map.js",
  "core/rect-bounds.js",
  "core/spatial-index.js",
  "core/state.js",
  "core/startup-flow.js",
  "core/timer-utils.js",
  "input/input-manager.js",
  "input/keyboard-controller.js",
  "input/sensor-controller.js",
  "input/sensor-watchdog.js",
  "maps/map-data.js",
  "platform/platform.js",
  "platform/viewport.js",
  "rendering/effects.js",
  "rendering/map-renderer.js",
  "rendering/marble-view.js",
  "rendering/obstacle-rendering.js",
  "rendering/rough-patch-rendering.js",
  "rendering/terrain-view.js",
  "rendering/trail.js",
  "rendering/wall-rendering.js",
  "rendering/ui.js",
  "settings/settings-applier.js",
  "settings/settings-config.js",
  "settings/settings-panel.js",
  "settings/settings-runtime.js",
  "settings/settings-store.js",
];

export const runtimeModuleScripts = runtimeScripts.filter(
  (script) => script !== "app.js",
);

export const runtimeStyles = ["style.css"];

export const runtimeFiles = [...runtimeScripts, ...runtimeStyles];
