export const runtimeScripts = [
  "app.js",
  "boot.js",
  "core/copy.js",
  "core/cockroach.js",
  "core/debug.js",
  "core/dom.js",
  "core/frame-loop.js",
  "core/goal-controller.js",
  "core/game-lifecycle.js",
  "core/game-loop.js",
  "core/geometry.js",
  "core/game-config.js",
  "core/haptics.js",
  "core/intro-sequence.js",
  "core/kitchen-dynamics.js",
  "core/map-bounds.js",
  "core/map-config.js",
  "core/map-elements.js",
  "core/map-obstacles.js",
  "core/map-objectives.js",
  "core/map-progression.js",
  "core/map-runtime.js",
  "core/map-variants.js",
  "core/mouse.js",
  "core/physics-collisions.js",
  "core/physics.js",
  "core/rect-bounds.js",
  "core/runtime-states.js",
  "core/state.js",
  "input/input-manager.js",
  "input/camera-controller.js",
  "input/camera-gestures.js",
  "input/keyboard-controller.js",
  "input/sensor-controller.js",
  "input/sensor-watchdog.js",
  "maps/map-data.js",
  "maps/map-authoring.js",
  "maps/kitchen-floor.js",
  "maps/kitchen-breakfast.js",
  "maps/living-room.js",
  "maps/parking-lot.js",
  "maps/kitchen-layout.js",
  "platform/platform.js",
  "rendering/effects.js",
  "rendering/cockroach-rendering.js",
  "rendering/goo-patch-rendering.js",
  "rendering/hazard-patch-rendering.js",
  "rendering/liquid-patch-shape.js",
  "rendering/kitchen-floor-details.js",
  "rendering/map-renderer.js",
  "rendering/map-theme-rendering.js",
  "rendering/living-room-rendering.js",
  "rendering/parking-lot-rendering.js",
  "rendering/marble-view.js",
  "rendering/mouse-rendering.js",
  "rendering/ice-patch-rendering.js",
  "rendering/obstacle-rendering.js",
  "rendering/rough-patch-rendering.js",
  "rendering/trail.js",
  "rendering/wall-rendering.js",
  "rendering/water-patch-rendering.js",
  "rendering/ui.js",
  "settings/settings-config.js",
  "settings/settings-panel.js",
  "settings/settings-store.js",
];

export const runtimeModuleScripts = runtimeScripts;

export const pwaFiles = [
  "manifest.webmanifest",
  "runtime-assets.js",
  "sw.js",
  "assets/icons/marble-icon.svg",
  "assets/icons/marble-maskable.svg",
  "assets/sprites/cheerio.png",
  "assets/sprites/fork.png",
  "assets/sprites/sponge.png",
  "assets/sprites/spoon.png",
  "assets/sprites/mouse.webp",
  "assets/sprites/shag.webp",
  "assets/sprites/oak-floor.webp",
  "assets/sprites/parking-asphalt.webp",
  "assets/sprites/parking-car.webp",
];

const runtimeStyles = ["style.css"];

export const runtimeFiles = [...runtimeScripts, ...runtimeStyles, ...pwaFiles];
