export const domIds = {
  game: "game",
  world: "world",
  introWalls: "introWalls",
  mapWalls: "mapWalls",
  roughPatches: "roughPatches",
  obstacles: "obstacles",
  goal: "goal",
  trail: "trail",
  trailSegments: "trailSegments",
  effects: "effects",
  marble: "marble",
  messageOverlay: "messageOverlay",
  controls: "controls",
  startBtn: "start",
  neutralBtn: "neutral",
  settingsToggle: "settingsToggle",
  settingsOverlay: "settingsOverlay",
  settingsTitle: "settingsTitle",
  closeSettings: "closeSettings",
  resumeGame: "resumeGame",
  speedSetting: "speedSetting",
  sensitivitySetting: "sensitivitySetting",
  rotationSetting: "rotationSetting",
  hapticsSetting: "hapticsSetting",
  trailSetting: "trailSetting",
  fullscreenSetting: "fullscreenSetting",
  fpsSetting: "fpsSetting",
  statsSetting: "statsSetting",
  cameraModeSetting: "cameraModeSetting",
  hint: "hint",
  fpsCounter: "fpsCounter",
  debug: "debug"
};

export const requiredDomIds = Object.values(domIds);
