export const appConfig = {
  fullscreenOnStart: true,
};

export const hapticTuning = {
  impactCooldownMs: 90,
  impactMin: 1.7,
  impactScale: 3,
  impactMinDurationMs: 8,
  impactMaxDurationMs: 35,
  surfaceCooldownMs: 130,
  surfaceMinSpeed: 1.2,
  surfaceScale: 1.4,
  surfaceMinDurationMs: 5,
  surfaceMaxDurationMs: 16,
  goalEnterDurationMs: 12,
  goalHoldDurationMs: 6,
  goalHoldCooldownMs: 900,
  goalCompletePattern: [18, 40, 28],
};

export const physicsConfig = {
  accel: 0.115,
  maxTilt: 26,
  smoothing: 0.2,
  friction: 0.94,
  bounce: 0.38,
  deadZone: 0.65,
  maxSpeed: 14,
  keyboardTilt: 18,
  maxStepDistance: 10,
  maxPhysicsSubsteps: 120,
  collisionResolvePasses: 1,
  collisionIndexCellSize: 256,
  roughPatchFriction: 0.96,
  scrapeHapticScale: 0.08,
  settleSpeed: 0.035,
  settleTilt: 0.8,
  tiltCurve: 1.25,
  maxSpeedEase: 0.35,
  wallTangentialFriction: 0.92,
  collisionEpsilon: 0,
};

export const timing = {
  introReleaseDelayMs: 5000,
  countdownTickMs: 1000,
  motionPermissionTimeoutMs: 1200,
  sensorFallbackMs: 1400,
  targetFrameMs: 16.67,
  minFrameStep: 0.25,
  maxFrameStep: 2,
};

export const tuning = {
  neutralSampleCount: 18,
  gestureCooldownFrames: 90,
  motionGravityScale: 3,
};

export const visualConfig = {
  trail: {
    durationMs: 2500,
    minDistance: 3,
    minIntervalMs: 50,
    maxOpacity: 0.5,
  },
  marble: {
    impactSquashDivisor: 12,
    impactSquashDecay: 0.12,
    impactScaleX: 0.08,
    impactScaleY: 0.06,
    glintCenter: 29,
    glintLightOffset: 11,
    glintVelocityScale: 0.08,
    glintVelocityLimit: 1.5,
  },
  effects: {
    impactMin: 1.9,
    impactReference: 10,
    impactCooldownMs: 70,
    maxParticles: 60,
    impactMinParticles: 2,
    impactExtraParticles: 5,
    impactEdgeRatio: 0.82,
    impactJitterRatio: 0.32,
    impactSpread: 18,
    impactDriftMin: 10,
    impactDriftRange: 24,
    impactSizeMin: 3,
    impactSizeRange: 4,
    impactLifeMinMs: 180,
    impactLifeRangeMs: 190,
    impactOpacity: 0.82,
    surfaceMinSpeed: 1.5,
    surfaceReferenceSpeed: 8,
    surfaceCooldownMs: 180,
    surfaceMinParticles: 1,
    surfaceExtraParticles: 2,
    surfaceBackRatio: 0.55,
    surfaceWidthRatio: 1.1,
    surfaceLiftMin: 2,
    surfaceLiftRange: 6,
    surfaceDriftMin: 6,
    surfaceDriftRange: 12,
    surfaceScatter: 0.08,
    surfaceSizeMin: 5,
    surfaceSizeRange: 7,
    surfaceLifeMinMs: 260,
    surfaceLifeRangeMs: 260,
    surfaceOpacity: 0.38,
  },
  map: {
    roughPatchCanvasPadding: 18,
    obstacleCanvasPadding: 32,
    goalFillEdgePercent: 70.8,
  },
};
