export const appConfig = {
  fullscreenOnStart: true,
};

export const hapticTuning = {
  impactCooldownMs: 90,
  impactMin: 1.7,
  impactScale: 3,
  impactMinDurationMs: 8,
  impactMaxDurationMs: 35,
  surfaceCooldownMs: 130,
  surfaceMinSpeed: 1.2,
  surfaceScale: 1.4,
  gooSurfaceScale: 1,
  waterSurfaceScale: 0.75,
  surfaceMinDurationMs: 5,
  surfaceMaxDurationMs: 16,
  goalEnterDurationMs: 12,
  goalHoldDurationMs: 6,
  goalHoldCooldownMs: 900,
  goalCompletePattern: [18, 40, 28],
};

export const physicsConfig = {
  // Motion tuning uses 60fps frame units: dt=1 means one target frame.
  // Retention values are exponentiated by dt, so they remain stable when the
  // game loop subdivides frames or renders slightly off cadence.
  accel: 0.115,
  maxTilt: 26,
  smoothing: 0.2,
  deadZone: 0.65,
  tiltCurve: 1.25,
  // Keyboard input maps to a fixed virtual tilt so desktop testing is stable.
  keyboardTilt: 18,
  maxSpeed: 14,
  baseDragRetention: 0.94,
  bounce: 0.38,
  maxStepDistance: 10,
  maxPhysicsSubsteps: 120,
  collisionResolvePasses: 1,
  gooPatchDragRetention: 0.72,
  icePatchDragRetention: 0.992,
  roughPatchDragRetention: 0.86,
  waterPatchDragRetention: 0.9,
  scrapeHapticScale: 0.08,
  settleSpeed: 0.035,
  settleTilt: 0.8,
  // Soft cap: 0 clamps exactly to maxSpeed, values above 0 retain overspeed.
  overspeedRetention: 0.35,
  wallTangentialDragRetention: 0.92,
  collisionDistanceSqEpsilon: 0,
  collisionZeroDistanceEpsilon: 0,
  collisionPositionSlop: 0,
};

export const timing = {
  introReleaseDelayMs: 5000,
  countdownTickMs: 1000,
  motionPermissionTimeoutMs: 1200,
  sensorFallbackMs: 1400,
  mapLabelDurationMs: 1800,
  // Physics dt is expressed in 60fps frame units: 1 equals targetFrameMs.
  targetFrameMs: 16.67,
  minFrameDelta: 0.25,
  maxFrameDelta: 2,
};

export const tuning = {
  neutralSampleCount: 18,
  gestureCooldownFrames: 90,
  motionGravityScale: 3,
  goalIndicatorDistanceMultiplier: 2.4,
  hazardRearmDistanceMultiplier: 3,
  hazardResetImpactFeedback: 12,
  antSquishImpactFeedback: 4.5,
  antSplatImpactFeedback: 2.1,
  cerealBumpImpactFeedback: 1.8,
  spongeSoakSurfaceFeedbackSpeed: 2.4,
};

export const visualConfig = {
  trail: {
    durationMs: 2500,
    minDistance: 3,
    minIntervalMs: 50,
    maxOpacity: 0.5,
  },
  marble: {
    impactSquashDivisor: 12,
    impactSquashDecay: 0.12,
    impactScaleX: 0.08,
    impactScaleY: 0.06,
    glintCenter: 29,
    glintLightOffset: 11,
    glintVelocityScale: 0.08,
    glintVelocityLimit: 1.5,
  },
  effects: {
    canvasScale: 0.5,
    canvasWorldSize: 1024,
    impactMin: 1.9,
    impactReference: 10,
    impactCooldownMs: 70,
    maxParticles: 60,
    impactMinParticles: 2,
    impactExtraParticles: 5,
    impactEdgeRatio: 0.82,
    impactJitterRatio: 0.32,
    impactSpread: 18,
    impactDriftMin: 10,
    impactDriftRange: 24,
    impactSizeMin: 3,
    impactSizeRange: 4,
    impactLifeMinMs: 180,
    impactLifeRangeMs: 190,
    impactOpacity: 0.82,
    gooSplatMinSpeed: 0.65,
    gooSplatReferenceSpeed: 7,
    gooSplatCooldownMs: 170,
    gooSplatSizeBase: 18,
    gooSplatSizeRange: 22,
    gooSplatLifeMs: 520,
    gooSplatOpacity: 0.58,
    waterRippleMinSpeed: 0.8,
    waterRippleReferenceSpeed: 8,
    waterRippleCooldownMs: 140,
    waterRippleSizeBase: 32,
    waterRippleSizeRange: 34,
    waterRippleLifeMs: 620,
    waterRippleOpacity: 0.5,
    goalCompleteParticles: 14,
    goalCompleteDriftMin: 22,
    goalCompleteDriftRange: 20,
    goalCompleteSizeMin: 4,
    goalCompleteSizeRange: 5,
    goalCompleteLifeMs: 620,
    goalCompleteOpacity: 0.88,
  },
  map: {
    gooPatchCanvasPadding: 24,
    hazardPatchCanvasPadding: 18,
    icePatchCanvasPadding: 18,
    roughPatchCanvasPadding: 18,
    waterPatchCanvasPadding: 24,
    obstacleCanvasPadding: 32,
    goalFillEdgePercent: 70.8,
  },
};
